name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle Wrapper
        run: |
          ./gradlew clean
          ./gradlew test
          ./gradlew build
      - name: Check for JAR file
        run: |
            if [ -f app/build/libs/app-0.0.1-SNAPSHOT.jar ]; then
              echo "JAR file exists"
            else
              echo "JAR file not found"
              exit 1
            fi      
      - name: List contents of jar file 
        run: |
          echo "Contents of app/build/libs:"
          ls -l app/build/libs    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: javaci/app:latest
